config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #ways to add a landing page, as syntax adds a route helper
  root to: "welcome#index"
  # get "/", to: "weclome#index", as: "welcome"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"

  resources :artists, only: [:new, :create, :show] do
    resources :songs, only: [:new, :create]
  end
  resources :songs, only: [:show, :index]
  resources :playlists, only: :index
  resources :users, only: [:new, :create, :show]

  # scope :admin, module: :admin, as: :admin do
  #   resources :categories, only: :index
  # end

  namespace :admin do
    resources :categories, only: :index
  end

  resources :carts, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs

  validates_presence_of :name

  def average_song_length
    songs.average(:length)
  end
end

app/models/cart.rb
class Cart

  attr_reader :contents

  def initialize(contents)
    @contents = contents || Hash.new(0)
  end

  def total_count
    @contents.values.sum
  end

  def add_song(id)
    @contents[id.to_s] = count_of(id) + 1
  end

  def count_of(id)
    @contents[id.to_s].to_i
  end
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :song
  belongs_to :playlist
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  has_many :playlist_songs
  has_many :playlists, through: :playlist_songs

  def self.song_count
    count
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  validates_presence_of :password, require: true

  has_secure_password

  enum role: [:default, :admin]
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404", status: 404 unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index

  end
end

app/controllers/admin/songs_controller.rb
class Admin::SongsController < Admin::BaseController
  def destroy
    song = Song.find(params[:id])
    song.destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include ActionView::Helpers::TextHelper

  helper_method :current_user, :current_admin?, :cart

private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def cart
    @cart ||= Cart.new(session[:cart])
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def new
    @artist = Artist.new
  end

  def create
    artist = Artist.new(artist_params)
    artist.save
    redirect_to "/artists/#{artist.id}"
  end

  def show
    @artist = Artist.find(params[:id])
    session[:secret] = "This time for real, though."
  end

  private

  def artist_params
    #add this for strong params/security reasons
    params.require(:artist).permit(:name)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def create
    song = Song.find(params[:song_id])
    cart.add_song(song.id)
    session[:cart] = cart.contents
    quantity = cart.count_of(song.id)
    flash[:notice] = "You now have #{pluralize(quantity, "copy")} of #{song.title} in your cart."
    redirect_to songs_path
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
    @playlists = Playlist.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(username: params[:username])
    if user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new
    @artist = Artist.find(params[:artist_id])
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.create(song_params)

    redirect_to song_path(@song)
  end

  private

  def song_params
    params.require(:song).permit(:title, :length, :play_count)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(new_params)
      if user.save
        flash[:message] = "Welcome #{user.username}!"
        redirect_to(songs_path)
      else
        render :new
      end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def new_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<h1>Admin Categories</h1>

app/views/artists/new.html.erb
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Set List</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <p><%= message %></p>
    <% end %>
    
    <p>Cart: <%= cart.total_count %></p>

    <%= yield %>
  </body>
</html>

app/views/playlists/index.html.erb
<% @playlists.each do |playlist| %>
  <section id=playlist-<%= playlist.id %>>
    <% playlist.songs.each do |song| %>
    <section id=song-<%= song.id %>>
      <%= song.title %>
    </section>
    <% end %>
  </section>
<% end %>

app/views/songs/index.html.erb
<% @songs.each do |song|%>
  <div id="song-<%= song.id %>-info">
    <h2><%= link_to song.title, "/songs/#{song.id}" %></h2>
    <p>Play Count: <%= song.play_count %></p>
    <p>Length: <%= song.length %></p>
    <% if current_admin? %>
      <%= button_to "delete", admin_song(song), method: :delete %>
    <% end %>
    <%= button_to "Add Song", carts_path(song_id: song.id) %>
  </div>
<% end %>

app/views/songs/new.html.erb
<%= form_for [@artist, @song] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :length %>
  <%= f.text_field :length %>

  <%= f.label :play_count %>
  <%= f.text_field :play_count %>

  <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h2><%= @song.title %></h2>
<p>By: <%= @song.artist.name %></p>
<p><%= @song.play_count %></p>
<p><%= @song.length %></p>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome, <%= current_user.username %>!</h1>
<%= link_to "Log Out", root_path %>

app/views/welcome/index.html.erb
<%= link_to "Register as User", new_user_path %>
<%= link_to "I already have an account", login_path %>